# Generated by Django 3.2.4 on 2021-07-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grdclc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataReqst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc', models.TextField()),
            ],
        ),
    ]
